### ISSUE TITLE
Image Bed

### ISSUE THREAD

**Issue by songquanpeng** [sharlylv/learn-web#1]
该 issue 被征用成一个图床，Win+Shift+S 截图后，在此处 Ctrl+V，即可将图片上传到 Github，之后复制图片链接即可。

**Comment by sharlylv** [comment]
![image](https://user-images.githubusercontent.com/47977849/100231973-b1ba2900-2f62-11eb-8091-31eb70b37966.png)

**Comment by songquanpeng** [comment]
关闭该 issue 不影响使用。
